export const SET_PRODUCT = "SET_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";

export const SET_SELECTED = "SET_SELECTED";
export const CLEAR_SELECTED = "CLEAR_SELECTED";

export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

export const READ_PRODUCTS_START = "READ_PRODUCTS_START";
export const READ_PRODUCTS_SUCCESS = "READ_PRODUCTS_SUCCESS";
export const READ_PRODUCTS_FAILURE = "READ_PRODUCTS_FAILURE";

export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const DELETE_MANY_PRODUCT_START = "DELETE_MANY_PRODUCT_START";
export const DELETE_MANY_PRODUCT_SUCCESS = "DELETE_MANY_PRODUCT_SUCCESS";
export const DELETE_MANY_PRODUCT_FAILURE = "DELETE_MANY_PRODUCT_FAILURE";

export const SET_VALUE = "SET_VALUE";
export const SET_VALUES = "SET_VALUES";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";
